services:
  drone-srcb:
    build: .
    environment:
      API_ID: $API_ID  
      API_HASH: $API_HASH  
      BOT_TOKEN: $1312141914:AAEaGViDWMh4xNXEknfXQUj1JsIKh-ndAjc
      SESSION: $SESSION
      AUTH: $AUTH
      FORCESUB: $FORCESUB
    ports:
      - 8080
    resources:
      cpu: 1000m
      memory: 3Gi
